---
language: python
python: "2.7"

env:
  - PLAYBOOK=playbook.yml

before_install:
  - ln -s ansible-role-mariadb ../aplyca.MariaDB

install:
  # Install Ansible.
  - sudo pip install paramiko PyYAML jinja2 httplib2
  - sudo pip install ansible

script:
  - tests/test.sh
  
notifications:
  email: false