---
language: python
python: "2.7"

env:
  - PLAYBOOK=playbook.yml

before_install:
  - ln -s ansible-role-mariadb ../aplyca.MariaDB

install:
    - sudo pip install -r tests/requirements.txt

script:
  - tests/test.sh
  
notifications:
  email: false