---
- name: Ensure MySQ client is present using apt
  sudo: yes
  apt:
    name: "{{ mariadb['packages']['client'] }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure MariaDB server is present using apt
  sudo: yes
  apt:
    name: "{{ mariadb['packages']['server'] }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  notify: start mysql
  when: mariadb.install_server

- name: Ensure Python MariaDB lib is present using apt
  sudo: yes
  apt:
    name: "python-mariadbdb"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: mariadb.install_server
